name: IaC Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'envs/prod/**'
      - '.github/workflows/terraform.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'envs/prod/**'

env:
  AWS_ACCOUNT_ID:     ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME:      ${{ secrets.AWS_ROLE_NAME }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  BUCKET_TF_STATE:    ${{ secrets.BUCKET_TF_STATE }}
  DYNAMO_DB_LOCK:     ${{ secrets.DYNAMO_DB_LOCK }}
  TF_DESTROY:         false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: Deploy VPC + EKS
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./envs/prod/infra/
    steps:
      - uses: actions/checkout@v4

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: ./envs/prod/infra/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            --backend-config="bucket=${BUCKET_TF_STATE}" \
            --backend-config="key=prod/infra/terraform.tfstate" \
            --backend-config="region=${AWS_DEFAULT_REGION}" \
            --backend-config="dynamodb_table=${DYNAMO_DB_LOCK}"

      - run: terraform fmt -check
      - run: terraform validate

      - name: Import existing access entry if exists
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_DESTROY == 'false' }}
        run: |
          terraform import \
            module.eks.aws_eks_access_entry.admin \
            retrogame-eks:arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:user/Tobi || true
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -lock=true -out=planfile --var-file=terraform.tfvars

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_DESTROY == 'false' }}
        run: terraform apply -lock=true -auto-approve planfile

      - name: Terraform Destroy
        if: ${{ env.TF_DESTROY == 'true' }}
        run: terraform destroy --var-file=terraform.tfvars -lock=false -auto-approve

  deploy-apps:
    name: Deploy Helm + Kubernetes Apps
    runs-on: ubuntu-latest
    needs: deploy-infra
    defaults:
      run:
        shell: bash
        working-directory: ./envs/prod/apps/
    steps:
      - uses: actions/checkout@v4

      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: ./envs/prod/apps/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            --backend-config="bucket=${BUCKET_TF_STATE}" \
            --backend-config="key=prod/apps/terraform.tfstate" \
            --backend-config="region=${AWS_DEFAULT_REGION}" \
            --backend-config="dynamodb_table=${DYNAMO_DB_LOCK}"

      - run: terraform fmt -check
      - run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -no-color \
            -input=false \
            -lock=true \
            -out=planfile \
            --var-file=terraform.tfvars \
            -var="grafana_password=${{ secrets.GRAFANA_PASSWORD }}"

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_DESTROY == 'false' }}
        run: terraform apply -lock=true -auto-approve planfile

      - name: Install kubectl
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_DESTROY == 'false' }}
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl

      - name: Verify Cluster Connection
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && env.TF_DESTROY == 'false' }}
        run: |
          aws eks update-kubeconfig --name retrogame-eks --region ${{ env.AWS_DEFAULT_REGION }}
          kubectl get nodes
          kubectl get pods -A

      - name: Delete manifests before destroy
        if: ${{ env.TF_DESTROY == 'true' }}
        run: |
          aws eks update-kubeconfig --name retrogame-eks --region ${{ env.AWS_DEFAULT_REGION }} || true
          kubectl delete -f ../../ingress.yaml --ignore-not-found || true
          kubectl delete -f ../../application.yaml --ignore-not-found || true

      - name: Terraform Destroy
        if: ${{ env.TF_DESTROY == 'true' }}
        run: |
          terraform destroy \
            --var-file=terraform.tfvars \
            -var="grafana_password=${{ secrets.GRAFANA_PASSWORD }}" \
            -lock=false \
            -auto-approve